hash-format = "sha256"

[[files]]
file = "config/promotedserver/servers.dat"
hash = "2065c37b24ba0658d9d2a181632952f447caf3c0fd004d7393a17984d73a3f3b"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "78568b988a30084520820c45d6f03de3442eca5800d77e870879200af28b5bc2"
metafile = true

[[files]]
file = "mods/promotedserver.pw.toml"
hash = "c95fe5b450d8eded1af2733a7b5b647ac63baaf8c5aa4cd00da3a7278127e124"
metafile = true

[[files]]
file = "mods/x-bar-theory.pw.toml"
hash = "c9a7e56ea1d681cbfd447b495a2f3f6ebf5fedd9b81d4febec5a76f6e14bfb6b"
metafile = true
